"use client";
import Header from "@/components/Header";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Provider as ReduxProvider } from "react-redux";
import Provider from "./Provider";
import store from "@/redux/store";
const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <ReduxProvider store={store}>
            <Header />
            {children}
          </ReduxProvider>
        </Provider>
      </body>
    </html>
  );
}
